title: Kent's blog
description: 路漫漫其修远兮
paginate: 5
paginate_path: "page:num"
show_downloads: true
theme: 
gems: [jekyll-paginate]
header-img: "img/banner.png"

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Analytics settings
# Baidu Analytics
ba_track_id: 8eb5262d38c50c342a631d2c55513271
# Google Analytics
ga_track_id: UA-91647085-1            # Format: UA-xxxxxx-xx
ga_domain: auto